framework: jest     
preRun:
  command:
    - yarn install          
postMerge:
  pattern: 
    - "./app/**/*.spec.ts"
    - "./app/**/*.test.ts"
    - "./addons/**/*.test.ts"
    - "./examples/**/*.spec.ts"
    - "./examples/**/*.test.js"
    - "./lib/**/*.test.ts"
preMerge:
  pattern:
    - "./app/**/*.spec.ts"
    - "./app/**/*.test.ts"
    - "./addons/**/*.test.ts"
    - "./examples/**/*.spec.ts"
    - "./examples/**/*.test.js"
    - "./lib/**/*.test.ts"
postRun:
  command:
    - yarn --version
version: 1.0
