framework: jest     
preRun:
  command:
    - yarn install          
postMerge:
  pattern: 
    - "./app/**/*.spec.ts"

preMerge:
  pattern:
    - "./app/**/*.spec.ts"

postRun:
  command:
    - yarn --version
version: 1.0
